spring:
  application:
    name: pilae-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ec2-54-159-35-35.compute-1.amazonaws.com:5432/daim8god4b1mh?user=dzaeodsgqcoznj&password=86902f87801cd7af734fe9eae0afdc4865d324e919fa3dd89de556e485b37bbd&sslmode=require}
    driver-class-name: org.postgresql.Driver
    platform: postgres
  flyway:
    baseline-version: 1.0
    baseline-on-migrate: true
    check-location: false
    sqlMigrationSuffixes: .sql
    schemas: public
    locations: classpath:db/migration,classpath:db/update